const SERVICES = {
  implants: {
    key: "implants",
    label: "Single Implant",
    shortLabel: "Implant",
    price: "€450",
    limassolPrice: "€1,600+",
    saving: "€1,150+",
    cardDescription: "Final price depends on bone condition and abutment type.",
    includes: ["Premium German / Swiss / Italian implant", "Standard abutment", "Surgical placement & guided planning"],
    tag: "Most popular",
    schemaName: "Dental Implants in Cyprus",
    schemaDescription: "Single dental implant treatment planning and clinic matching in Cyprus.",
  },
  crowns: {
    key: "crowns",
    label: "Zirconia Crown",
    shortLabel: "Crown",
    price: "€190",
    limassolPrice: "€500+",
    saving: "€310+",
    cardDescription: "Final price depends on tooth position and shade complexity.",
    includes: ["Full-anatomic zirconia crown", "Digital scan & CAD/CAM milling", "Final cementation"],
    tag: null,
    schemaName: "Dental Crowns in Cyprus",
    schemaDescription: "Dental crown treatment planning with vetted Cyprus implant clinics.",
  },
  allOn: {
    key: "allOn",
    label: "All-on-4 / All-on-6",
    shortLabel: "All-on-4/6",
    price: "€4,750",
    limassolPrice: "€13,000+",
    saving: "€8,250+",
    cardDescription: "Final price depends on bone anatomy, framework choice and arch.",
    includes: ["4 or 6 premium implants per arch", "Titanium bar or zirconia bridge", "Same-day temporary in eligible cases"],
    tag: "Best value",
    schemaName: "All-on-4 / Full-Arch Implants in Cyprus",
    schemaDescription: "Full-arch implant treatment planning and referral in Cyprus.",
  },
  hollywood: {
    key: "hollywood",
    label: "Hollywood Smile",
    shortLabel: "Hollywood Smile",
    price: "€3,500",
    limassolPrice: "€8,000+",
    saving: "€4,500+",
    cardDescription: "Full digital smile design · AI preview · Premium zirconia veneers.",
    includes: ["Digital smile design", "AI preview", "Premium zirconia veneers"],
    tag: "Signature Package",
    schemaName: "Hollywood Smile in Cyprus",
    schemaDescription: "Hollywood Smile treatment planning and referral support in Cyprus.",
  },
} as const;

export const SITE = {
  brand: "Dental Implant Experts Cyprus",
  shortBrand: "Implant Experts Cyprus",
  tagline: "Premium Implant & Smile Design in Cyprus",
  advisorLabel: "Independent Dental Travel Advisory",
  advisorDesc:
    "Independent dental travel advisory — connecting international patients with Cyprus's top-rated specialist implant clinic.",
  whatsappNumber: "+35797000000",
  whatsappLink:
    "https://wa.me/35797000000?text=Hello%2C%20I%27d%20like%20a%20free%20treatment%20plan%20for%20dental%20implants%20in%20Cyprus.",
  rating: "5.0",
  reviews: "159+",
  services: SERVICES,
  serviceKeys: ["implants", "crowns", "allOn", "hollywood"] as const,
  heroServiceKeys: ["implants", "allOn", "hollywood"] as const,
  regularServiceKeys: ["implants", "crowns", "allOn"] as const,
  prices: {
    implants: SERVICES.implants.price,
    crowns: SERVICES.crowns.price,
    hollywood: SERVICES.hollywood.price,
    allOn: SERVICES.allOn.price,
  },
  limassolPrices: {
    implants: SERVICES.implants.limassolPrice,
    crowns: SERVICES.crowns.limassolPrice,
    hollywood: SERVICES.hollywood.limassolPrice,
    allOn: SERVICES.allOn.limassolPrice,
  },
};
